name: 'iqra-sbms'

services:
    frontend:
        build:
            context: ./client
        container_name: frontend
        ports:
            - 3000:80
        depends_on:
            - backend
        volumes:
            - deps:/home/iqra-sbms-client/node_modules
        develop:
            watch:
                - action: rebuild
                  path: ./client/src
                  target: /home/iqra-sbms-client
                  ignore:
                    - node_modules

    backend:
        build:
            context: ./server
        container_name: backend
        ports:
            - 5000:5000
        environment:
            - ENV=dev
            - DEBUG=0
            - API_HOST=0.0.0.0
            - API_PORT=5000
            - DATA_DIR=./seed
            - DB_HOST='127.0.0.1'
            - DB_PORT=52002
            - DB_USER=iqra
            - DB_PASS=iqra
            - DB_NAME=iqra-db
            - JWT_SECRET_KEY=12345
            - JWT_COOKIE_DOMAIN=localhost
            - JWT_ACCESS_COOKIE_NAME=iqra-auth
            - JWT_ACCESS_CSRF_COOKIE_NAME=iqra-csrf
            - JWT_ACCESS_TOKEN_EXPIRES=60
            - CORS_ORIGINS=*
            - ADMIN_ID=111-111-1111
            - ADMIN_PASS=12345
            - STUDENTS_SYSTEM_BASE_URL=https://enrollment-system.vercel.app/api/
            - STUDENTS_SYSTEM_API_KEY=1234
        depends_on:
            - db
        develop:
            watch:
                - action: rebuild
                  path: ./server

    db:
        image: mysql
        container_name: database
        restart: always
        ports:
            - 52002:3306
        environment:
            - MYSQL_ROOT_PASSWORD=iqra
            - MYSQL_DATABASE=iqra-db
            - MYSQL_USER=iqra
        volumes:
            - data:/var/lib/mysql

volumes:
    deps:
    data: