"""empty message

Revision ID: 75540de82de2
Revises: 
Create Date: 2024-10-06 23:50:56.583342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75540de82de2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('balance')
        batch_op.drop_column('total_paid')

    # ### end Alembic commands ###
